version: '3.3'

services:
  web:
    # Берем Dockerfile из каталога app
    build: ./xsolla
    # Запускаем тестовый сервер
    command: python manage.py runserver 0.0.0.0:8000
    
    # Вариант с запуском без режима отладки со сборкой статики не удалось отработать:
    # command: sh -c "python manage.py collectstatic -c --noinput && python manage.py runserver 0.0.0.0:8000"
    # Статика собирается, но не раздаётся
    
    # куда будут помещены данные из каталога app
    volumes:
      - ./xsolla/:/usr/src/xsolla/
    # Пробрасываем порт 8000 из контейнера на порт 80 хоста
    ports:
      - 80:8000
    # Файл содержащий переменные для контейнера
    env_file:
      - ./.env.dev
